### ISSUE TITLE
IndexOutOfBoundsException when launching with several input files of the same type.

### ISSUE THREAD

**Issue by opcoach** [dupuisa/i-CodeCNES#63] opened 2017-07-20 17:31 UTC
I got this exception when I launch the check on several files of the same type (fortran for instance).
Only the results of the first file are displayed. 

If I launch the command with a shell and a fortran, there is not exception. 

java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at fr.cnes.analysis.tools.analyzer.Analyzer.check(Analyzer.java:130)
	at fr.cnes.icode.application.ICodeApplication.start(ICodeApplication.java:181)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at fr.cnes.analysis.tools.fortran77.rules.COMPROJECTHeader.raiseErrors(COMPROJECTHeader.java:438)
	at fr.cnes.analysis.tools.fortran77.rules.COMPROJECTHeader.run(COMPROJECTHeader.java:842)
	at fr.cnes.analysis.tools.analyzer.CallableChecker.call(CallableChecker.java:53)
	at fr.cnes.analysis.tools.analyzer.CallableChecker.call(CallableChecker.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by WaldoFR** [comment] 2017-08-02 12:43
Hello Olivier,

Can you reproduce this bug every time you run an analysis with several Fortran files ?

Do you still have an access to the files causing this crash ? It seems that the problem come directly from the rule COM.PROJECT.Header of the language Fortran77. I'd like to determine if this issue is a new one concerning the `Analyzer` or if it's a duplicate of #47.

If you reach only the result of the first file, it might be due to the fact that it is the second file which is causing the crash of the analysis.

Regards,
Omar

**Comment by WaldoFR** [comment] 2017-08-03 09:48
After investigation of this issue, launching analysis on heavy list of fortran files, I've been able to reproduce out of bound exceptions reported. 

The problem come from **COM.PROJECT.Header** rule, it's a duplicate of #47, we'll handle it soon.

Thank you for having reported it.

Regards,
Omar

**Comment by WaldoFR** [comment] 2017-08-04 13:21
Running an analysis without the rule **COM.PROJECT.Header** do not display an exception but is having same behaviour as the reported bug. 

This issue is not a duplicate of #47 and must be reopened.

**Comment by WaldoFR** [comment] 2017-08-21 15:32
This issue was re-opened while solving #82 issue. Exception of type `IndexOutOfBound` exception raisen from the rule **COM.PROJECT.Header** aren't the cause of the undisplayed element.

As related in the limitation #24 , it's not possible to reuse the method `setInputFile()`. That's why the `Analyzer` is using `CallableChecker` jobs to run it's analysis that are only intended to : 
* Use only one's rule analyzer.
* Parse only one file.

However the `getChecker()` method of the class `CheckerContainer` that was being called by the `Analyzer` to instansiate the new `CallableChecker` was returning the same `AbstractChecker` and not a cloned one which had for consequence to share the sames buffer as the `AbstractChecker` used to parse older files. This even if the `setInputFile()` was called in separated clones.

**Closed** 2017-08-22 09:07 UTC
Labels: bug
